### ISSUE TITLE
Семантика

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/ui-kit-full#14]
По какой логике принимается решение об использовании h1-h6 либо p?

В news заголовок лежит в `<h2>`, а дата в `<p>`, а в event наоборот - дата в `<h2>`, а заголовок в `<p>`

![Снимок экрана от 2020-04-05 23-10-53](https://user-images.githubusercontent.com/38564412/78508910-ffdfa980-7792-11ea-9efe-cb4208ce06ae.png)
![Снимок экрана от 2020-04-05 23-12-13](https://user-images.githubusercontent.com/38564412/78508913-00784000-7793-11ea-9998-aaee031e7ff0.png)

**Comment by RomKmeister** [comment]
Здесь никакой логики, только невнимательность (
