### ISSUE TITLE
Общие замечания

### ISSUE THREAD

**Issue by Feinminen** [RomKmeister/ui-kit-full#26]
Тут всё не критично, но всёж :)
1) С точки зрения UI при нажатии кнопок, они должны опускаться вниз, как будтно на неё нажали, а у тебя сейчас 'тень' притягивается к кнопке.
![2_implementation](https://user-images.githubusercontent.com/44312820/85004394-b42d8100-b181-11ea-83e6-ca77844041f6.gif)
![1_implementation](https://user-images.githubusercontent.com/44312820/85004396-b55eae00-b181-11ea-84e9-d55868bc30fe.gif)

2)При клике на сабмит должна предотваращаться отправка формы, чтобы ошибка запроса не выкидывалалсь

3)Это явно кнопки, а не просто иконки
![image](https://user-images.githubusercontent.com/44312820/85008975-ec37c280-b187-11ea-9e52-d20716609f88.png)

4)При клике на кнопку переключения на календаре курсор может быть не поинтером. Т.е. кнопка значительно больше по области, чем область на которой курсор - поинтер.
![pointer](https://user-images.githubusercontent.com/44312820/85010049-95cb8380-b189-11ea-96f5-51ad59880d1b.gif)

5)Не совсем понимаю зачем на всех элементах ярко выраженная обводка, в каких-то местах прям очень странно выглядит.
![outline](https://user-images.githubusercontent.com/44312820/85010255-e511b400-b189-11ea-820f-65c5606d1c90.gif)

6)Сейчас при клике на эроу батоны такое поведение, что после клика кнопка остаётся активной, что, имхо, немного странно. Выглядит так, как-будтно кнопка 'залипла'
![arrows](https://user-images.githubusercontent.com/44312820/85010424-2d30d680-b18a-11ea-94b8-5ea3b56504fa.gif)

7)Эти блоки должны же быть одинаковыми по высоте
![image](https://user-images.githubusercontent.com/44312820/85010519-56e9fd80-b18a-11ea-8226-6dc8f54d5aa2.png)

**Comment by Feinminen** [comment]
Сейчас максимальное значение у слайдера 110. Если так было задумано - то, в целом, ок, а если нет - то надо поменять.
![image](https://user-images.githubusercontent.com/44312820/86513090-7b540400-be31-11ea-82fa-fd2dd633d08a.png)

**Comment by Feinminen** [comment]
Неиспользуемые аргументы методов/функций принятно называть нижними подчеркиваниями. Причем если не используется первый аргумент, то будет одно подчеркивание, а если второй - два и т.д. (_, __, usedArg);
![image](https://user-images.githubusercontent.com/44312820/86513265-f2d66300-be32-11ea-82d8-983f244e0f0c.png)
Т.е. если в данном примере сделать вот так slide: (_, ui) - то и компилятор ts-a(если бы это был ts) и IDE не будет как незаюзанный аргумент помечать.
Посмотри по всему проекту, я много где видел.

**Comment by RomKmeister** [comment]
> Cейчас максимальное значение у слайдера 110. Если так было задумано - то, в целом, ок, а если нет - то надо поменять.

Если поставить 100, то ползунок на 40 не совпадал с макетом, а если 110, то все ок, поэтому поставил 110.
