### ISSUE TITLE
Баги в проекте

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/ui-kit-full#4]
В календаре при нажатии на today устанавливается только месяц, а день не выделяется активным:

![calendar](https://user-images.githubusercontent.com/38564412/76458764-19880e00-63ec-11ea-8260-f71ebbce4598.gif)

**Comment by MorganaLF** [comment]
Error и thanks висят постоянно, а по идее должны появляться после валидации введенных полей

![Снимок экрана от 2020-03-11 23-01-23](https://user-images.githubusercontent.com/38564412/76458922-5c49e600-63ec-11ea-8ce8-d708abe0ab8b.png)

**Comment by MorganaLF** [comment]
Тоглы работают, а вот чекбоксы некликабельны

![checkboxes](https://user-images.githubusercontent.com/38564412/76459079-99ae7380-63ec-11ea-8b52-9c728099c8ab.gif)

**Comment by MorganaLF** [comment]
Этот слайдер должен передвигаться по отметкам шкалы, т.е. по шагам, а у тебя сейчас его можно передвинуть в любое место

![slider](https://user-images.githubusercontent.com/38564412/76459237-de3a0f00-63ec-11ea-887c-d351de6e6f73.gif)

**Comment by MorganaLF** [comment]
У этого слайдера не по центру выровнен bubble

![Снимок экрана от 2020-03-11 23-06-40](https://user-images.githubusercontent.com/38564412/76459353-0f1a4400-63ed-11ea-9c27-32e1bf727a4e.png)

**Comment by MorganaLF** [comment]
Я думаю, что это всё-таки чекбоксы, а не радиокнопки: это и из названия следует, и по внешнему виду тоже понятно

![Снимок экрана от 2020-03-30 22-14-50](https://user-images.githubusercontent.com/38564412/77952233-f9a18700-72d3-11ea-896f-33281760d96b.png)

**Comment by MorganaLF** [comment]
> Я думаю, что это всё-таки чекбоксы, а не радиокнопки: это и из названия следует, и по внешнему виду тоже понятно

Этот момент не исправлен, здесь что-то непонятно, или просто случайно пропустил?

**Comment by RomKmeister** [comment]
> Этот момент не исправлен, здесь что-то непонятно, или просто случайно пропустил?
Случайно пропустил.
