### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/ui-kit-full#8]
По стандартам требуется использовать линтер на проекте, пункт 2 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

Сейчас линтер не настроен. Сразу скажу, что он должен быть настроен под AirBnB, плюс желательно добавить команду для линтинга, чтобы можно было запустить и посмотреть ошибки.

**Comment by MorganaLF** [comment]
А для чего задисейблено правило no-undef?

![Снимок экрана от 2020-03-30 22-36-24](https://user-images.githubusercontent.com/38564412/77954221-fe1b6f00-72d6-11ea-8b46-991e3a4647c2.png)

**Comment by RomKmeister** [comment]
Подключил правило из-за яндекс карт, линтер ругался на ymaps

**Comment by MorganaLF** [comment]
Но ты ведь таким образом отключил правило для всего проекта, из-за чего могут быть пропущены ошибки. Сейчас ты указал правило локально в файле, но можно обойтись вообще без отключения правила, указав, что это глобальная переменная: https://eslint.org/docs/rules/no-undef
