### ISSUE TITLE
Переменные scss

### ISSUE THREAD

**Issue by MorganaLF** [RomKmeister/ui-kit-full#9]
Мне кажется, сейчас не очень удобное именование переменных, есть ведь цвета, которые теоретически могут поменяться. Например, тебе нужно будет во всем проекте заменить красный цвет на синий, а зеленый на оранжевый. И придется во всем проекте менять имена переменных. А по идее должна быть возможность поменять цветовую схему из одного места - из файла с переменными. 

![Снимок экрана от 2020-03-24 10-13-29](https://user-images.githubusercontent.com/38564412/77398205-2297b880-6db8-11ea-8519-f30edf0b97c5.png)

Следующий вопрос, почему так мало используются возможности препроцессоров: где, например, переменные для брейкпойнтов? Нет ни одного миксина, как минимум, можно было бы сделать миксин для подключения шрифтов, чтобы не писать сто раз одно и то же. В общем, нужно подумать, как и где можно себе упростить жизнь, используя css-препроцессоры.

![Снимок экрана от 2020-03-24 10-14-53](https://user-images.githubusercontent.com/38564412/77398325-58d53800-6db8-11ea-9531-415f1d749006.png)

**Comment by MorganaLF** [comment]
Здесь у тебя используются цвета из имеющейся палитры, лучше использовать классы и переменные

![Снимок экрана от 2020-03-24 10-35-11](https://user-images.githubusercontent.com/38564412/77399943-75bf3a80-6dbb-11ea-917c-99416ea59a9d.png)

**Comment by MorganaLF** [comment]
Вот здесь тоже, например, почему бы локально не заюзать переменную для рамки, чтобы не повторяться постоянно

![Снимок экрана от 2020-03-24 10-56-43](https://user-images.githubusercontent.com/38564412/77401582-3b0ad180-6dbe-11ea-9438-afcb249c9d13.png)

**Comment by MorganaLF** [comment]
Теперь с именами переменных другая проблема) С `$main` согласна. Но second и third это уже пошла какая-то нумерация, не несущая в себе никакого смысла. 

Какую роль может играть цвет? Он может быть основным, второстепенным, акцентным и т.п. Первый-второй-третий цвет - это бессмысленно. Также можно указать, что у тебя есть главный/второстепенный цвет для шрифта, например. 

Цвета вроде черного/белого/серых в принципе можно называть собственными именами, потому что скорее всего они такими и останутся при замене цветовой схемы. В общем, когда даешь имена переменных, нужно попытаться представить, как они тебе помогли бы при долгосрочной поддержке проекта.

![Снимок экрана от 2020-03-30 22-46-47](https://user-images.githubusercontent.com/38564412/77955451-e6dd8100-72d8-11ea-8443-97d913b16e68.png)

**Comment by MorganaLF** [comment]
Для брейкпойнтов немного странные имена переменных, обычно брейкпойнты устанавливают в зависимости от ширины различных девайсов: mobile, tablet, и т.п., думаю, переменные должны отражать это

![Снимок экрана от 2020-03-30 22-52-55](https://user-images.githubusercontent.com/38564412/77955763-6cf9c780-72d9-11ea-9e86-6c33066e3918.png)

**Comment by MorganaLF** [comment]
Не забываем подстраховываться, если в color оказалась какая-то дичь)

![Снимок экрана от 2020-03-30 22-58-20](https://user-images.githubusercontent.com/38564412/77956137-0de88280-72da-11ea-9af9-e0fb266f43e1.png)

**Comment by RomKmeister** [comment]
А нужно изменять имена классов, например .standard-button_color_green, должен стать .standard-button_color_main, а в паге должны быть переменные main, additional, и т.д. ?

**Comment by RomKmeister** [comment]
> Не забываем подстраховываться, если в color оказалась какая-то дичь)
Я сделал постоянный фон, который отображается всегда, а данные откусывают у него свои части, если  передать дичь, то будет серый кружок. Лучше заменить на дефолтную переменную?
![123](https://user-images.githubusercontent.com/46928144/78059651-8149cd00-738a-11ea-871d-4941dbbcca60.jpg)
![111](https://user-images.githubusercontent.com/46928144/78059566-5c555a00-738a-11ea-9f94-c257581ba5b4.jpg)

**Comment by MorganaLF** [comment]
> А нужно изменять имена классов, например .standard-button_color_green, должен стать .standard-button_color_main, а в паге должны быть переменные main, additional, и т.д. ?

Обычно для цветов дают имена primary/secondary, это более привычно звучит. Для классов, думаю, да, имеет тоже смысл дать такие универсальные имена.

**Comment by MorganaLF** [comment]
> Я сделал постоянный фон, который отображается всегда, а данные откусывают у него свои части, если передать дичь, то будет серый кружок. Лучше заменить на дефолтную переменную?

Ну в принципе визуально рабочее решение, но мне кажется странной ситуация, что в html болтается какой-то класс на элементе, а по факту этот класс никак не отрабатывает

![Снимок экрана от 2020-03-31 22-32-41](https://user-images.githubusercontent.com/38564412/78067541-93823600-739f-11ea-964c-72780a1da85d.png)


![Снимок экрана от 2020-03-31 22-31-26](https://user-images.githubusercontent.com/38564412/78067502-7ea5a280-739f-11ea-987c-de214a7996a0.png)

**Comment by RomKmeister** [comment]
Сделал еще вариант переменных, пришлось разбивать цвета на $backgroung и $content, потому что если нужна заменяемость, то нельзя сделать переменную $white, она будет привязана к разным элементам, меняя фон на синий зацепится и цвет текста, а во-вторых это константа, $white не может быть #0000ff.
Хотел ввести изначально переменную $text, но цветами текста иногда покрашен не текст, а что-то похожее, поэтому взял более абстрактное имя. Иногда приходится странно использовать,
{ border-color: $content-primary } 
но мне кажется по смыслу здесь border нужна для отрисовки стрелки, которую можно отнести к контенту.

В целом меня смущает, что мы привязываем все блоки к глобальным переменным. Это поможет, если дизайнер попросит изменить всю цветовую схему. Но он может попросить изменить отдельный элемент и тогда будут сложности:
Придется создавать новые переменные с абстрактными именами, которые закончатся быстрее чем цвета. Дальше нужно добавлять их в свойства в цсс, где стало сложнее разобраться, потому что имена абстрактны, чтобы понять что такое primary надо посмотреть в файл переменных.

Кажется, если бы в свойствах были просто имена цветов, то с помощью автозамены все было бы проще
Все цвета в проекте или в отдельном файле можно изменить одним действием как и за счет переменных
#ffffff -> #0000ff
Если надо только фоны, то 
background: #ffffff -> background: #0000ff 
при этом я знаю, что точно не зацепил ничего кроме фонов.
Классы подсказывают что в них находится, и меняются тоже одним действием
&_white -> &_blue
Причем если нужно поменять оттенок цвета, то классы не надо переименовывать.
Могут сломаться сокращенные классы background: #ffffff url(), но можно использовать background-color.

**Comment by MorganaLF** [comment]
> В целом меня смущает, что мы привязываем все блоки к глобальным переменным. Это поможет, если дизайнер попросит изменить всю цветовую схему. Но он может попросить изменить отдельный элемент и тогда будут сложности:
Придется создавать новые переменные с абстрактными именами, которые закончатся быстрее чем цвета. Дальше нужно добавлять их в свойства в цсс, где стало сложнее разобраться, потому что имена абстрактны, чтобы понять что такое primary надо посмотреть в файл переменных.

Я с тобой согласна, но я ведь и не писала, что нужно вообще абсолютно все цвета делать абстрактными. Просто в макете есть обычно несколько основных цветов, их как правило не много, и именно они с наибольшей вероятностью могут поменяться вообще во всем проекте глобально. Остальные цвета, встречающиеся редко, имеет смысл называть своими именами.

В этом проекте наиболее очевидные - это красный и зеленый цвет. Это точно кандидаты на абстрактные имена.
Можешь для примера посмотреть, как это устроено в различных библиотеках - обычно есть primary и secondary цвета, какой-нибудь primaryTextColor, а остальное своими именами.
Просто учитывая, что в этом задании у нас UI-кит, у него все-таки должна быть какая-то универсальность.
